### ISSUE TITLE
Excessive logging by REST service

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard-rest#1]
Each incoming request in https://github.com/clarin-eric/LRSwitchboard-rest/blob/master/index.js is logged to the console. There is also logging to the console in the loops of https://github.com/clarin-eric/LRSwitchboard-rest/blob/master/Matcher.js. This generates a lot of log output for a single LRS session. This logging should be optional, ideally using a logging framework that supports log levels.

**Comment by emanueldima** [comment]
The Switchboard has a new backend now, so this issue is no longer valid.
